const fs = require('fs');
const path = require('path');

const storePath = path.join(__dirname, '../src/store/useProductStore.ts');

const NEW_PRODUCTS_JSON = [
  // ==================== HOT DRINKS (Boissons chaudes) ====================
  { id: "1", category_id: "coffee", name: "Espresso", description: "Espresso classique intense, riche en arômes.", price: 150, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: true, featured: false, promotion: false, ingredients: "Café de spécialité" },
  { id: "2", category_id: "coffee", name: "Espresso Arabica & Robusta", description: "Mélange équilibré de grains Arabica et Robusta.", price: 250, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Grains Arabica & Robusta" },
  { id: "3", category_id: "coffee", name: "Capsule Caps", description: "Café en capsule Caps préparé avec soin.", price: 250, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Capsule Caps" },
  { id: "4", category_id: "coffee", name: "Capsule L'Or", description: "Café de capsule de marque L'Or Espresso.", price: 300, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Capsule L'Or" },
  { id: "5", category_id: "coffee", name: "Capsule Nespresso", description: "Café en capsule premium Nespresso.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Capsule Nespresso" },
  { id: "6", category_id: "coffee", name: "Americano", description: "Double shot d'espresso allongé à l'eau chaude.", price: 300, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Espresso, eau chaude" },
  { id: "7", category_id: "coffee", name: "Cafe Latte", description: "Espresso mélangé à du lait chaud avec une fine couche de mousse.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Espresso, lait chaud, mousse" },
  { id: "8", category_id: "coffee", name: "Chocolate Milk", description: "Lait crémeux délicieusement chocolaté.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Lait, chocolat fondu" },
  { id: "9", category_id: "coffee", name: "Piccolo Latte", description: "Ristretto court garni de lait velouté chaud.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Ristretto, lait chaud" },
  { id: "10", category_id: "coffee", name: "Latte Macchiato", description: "Lait chaud, mousse onctueuse et shot d'espresso superposé.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: true, promotion: false, ingredients: "Lait, espresso" },
  { id: "11", category_id: "coffee", name: "Cortado", description: "Espresso coupé avec une quantité égale de lait chaud.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Espresso, lait chaud" },
  { id: "12", category_id: "coffee", name: "Cinnamon Latte", description: "Latte parfumé à la cannelle pour une touche épicée.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Espresso, lait, sirop de cannelle" },
  { id: "13", category_id: "coffee", name: "Cafe Bombon", description: "Espresso servi avec du lait concentré sucré.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Espresso, lait concentré sucré" },
  { id: "14", category_id: "coffee", name: "Cappuccino", description: "Un tiers espresso, un tiers lait chaud, un tiers mousse.", price: 400, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: true, featured: true, promotion: false, ingredients: "Espresso, lait chaud, mousse" },
  { id: "15", category_id: "coffee", name: "Cafe Mocha", description: "Espresso, chocolat chaud et lait cuit à la vapeur.", price: 400, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Espresso, chocolat, lait" },
  { id: "16", category_id: "coffee", name: "Flat White", description: "Double ristretto garni de lait micro-mousse onctueux.", price: 400, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Double ristretto, lait chaud" },
  { id: "17", category_id: "coffee", name: "Hot Chocolate", description: "Chocolat chaud onctueux fait maison.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Chocolat noir, lait chaud, cacao" },
  { id: "18", category_id: "coffee", name: "Matcha Latte", description: "Thé matcha japonais traditionnel et lait crémeux.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: true, promotion: false, ingredients: "Matcha de cérémonie, lait chaud" },
  { id: "19", category_id: "coffee", name: "Ube Latte", description: "Boisson originale à base d'ube (igname violet) et de lait.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Ube, lait chaud" },

  // ==================== COLD DRINKS (Boissons fresh) ====================
  { id: "20", category_id: "cold-drinks", name: "Iced Latte", description: "Espresso et lait frais versés sur de la glace.", price: 400, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Espresso, lait, glaçons" },
  { id: "21", category_id: "cold-drinks", name: "Iced Caramel Macchiato", description: "Espresso glacé au caramel fondant et lait.", price: 450, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: true, ingredients: "Espresso, caramel, lait, glaçons" },
  { id: "22", category_id: "cold-drinks", name: "Iced Spanish Latte", description: "Café glacé doux et crémeux préparé avec du lait condensé.", price: 450, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: true, featured: true, promotion: false, ingredients: "Espresso, lait concentré, lait, glaçons" },
  { id: "23", category_id: "cold-drinks", name: "Iced Mocha Latte", description: "Café glacé chocolaté et rafraîchissant.", price: 450, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Espresso, chocolat, lait, glaçons" },
  { id: "24", category_id: "cold-drinks", name: "Affogato", description: "Espresso chaud versé sur une boule de glace vanille.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Glace vanille, espresso chaud" },
  { id: "25", category_id: "cold-drinks", name: "Dalgona Coffee", description: "Lait frais surmonté d'une mousse de café fouettée.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Mousse de café fouettée, lait, glaçons" },
  { id: "26", category_id: "cold-drinks", name: "Iced Matcha Latte", description: "Matcha japonais servi glacé avec du lait.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Matcha, lait, glaçons" },
  { id: "27", category_id: "cold-drinks", name: "Iced Ube", description: "Lait à l'ube violet glacé et onctueux.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Ube, lait, glaçons" },
  { id: "28", category_id: "cold-drinks", name: "Iced Matcha", description: "Matcha pur préparé à l'eau et servi sur glace.", price: 650, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Matcha pur, eau, glaçons" },
  { id: "29", category_id: "cold-drinks", name: "Iced Tea", description: "Thé infusé glacé, fruité et rafraîchissant.", price: 400, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Thé noir infusé, citron, menthe, glaçons" },

  // ==================== MOCKTAILS (Mocktail) ====================
  { id: "30", category_id: "mocktails", name: "Cocktail Solo (Orange, Banane, Fraise)", description: "Jus de fruits frais pressés de saison au choix.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Jus de fruits frais pressés" },
  { id: "31", category_id: "mocktails", name: "Pina Colada", description: "Cocktail tropical à base d'ananas et coco.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Jus d'ananas, crème de coco, glaçons" },
  { id: "32", category_id: "mocktails", name: "Bora Bora", description: "Cocktail fruité et coloré aux saveurs des îles.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Jus de fruits exotiques, sirop" },
  { id: "33", category_id: "mocktails", name: "Virgin Sunrise", description: "Mélange fruité à l'orange et grenadine.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Jus d'orange, sirop de grenadine" },
  { id: "34", category_id: "mocktails", name: "Pink Lady", description: "Cocktail onctueux et fruité aux notes de grenadine.", price: 550, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Jus de pamplemousse, grenadine, crème" },
  { id: "35", category_id: "mocktails", name: "There Will Be Blood", description: "Cocktail rouge intense aux baies sauvages.", price: 650, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Jus de grenade, baies, sirop" },
  { id: "36", category_id: "mocktails", name: "Detox", description: "Jus vert ultra-frais et revitalisant.", price: 650, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Concombre, pomme verte, menthe, citron" },
  { id: "37", category_id: "mocktails", name: "Fruit Cocktail", description: "Mélange de saison de fruits frais mixés.", price: 700, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Fruits de saison frais" },
  { id: "38", category_id: "mocktails", name: "Healthy", description: "Jus pressé énergisant et vitaminé.", price: 1000, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: true, promotion: false, ingredients: "Gingembre, carotte, orange, citron" },
  { id: "39", category_id: "mocktails", name: "Mojito Classic", description: "Menthe fraîche, citron vert vert pressé et soda.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: true, featured: true, promotion: false, ingredients: "Citron vert, menthe, soda, sucre de canne" },
  { id: "40", category_id: "mocktails", name: "Mojito Red", description: "Mojito rafraîchissant aux fruits rouges.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Menthe, citron, soda, sirop de fraise/framboise" },
  { id: "41", category_id: "mocktails", name: "Mojito Blue Ocean", description: "Mojito bleu électrique au curaçao.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Menthe, citron, soda, sirop de curaçao bleu" },
  { id: "42", category_id: "mocktails", name: "Mojito Exotic", description: "Mojito exotique aux fruits de la passion.", price: 650, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Menthe, citron, soda, fruits de la passion" },

  // ==================== SMOOTHIES (Smoothies) ====================
  { id: "43", category_id: "smoothies", name: "Smoothie Classic Banana", description: "Banane onctueuse mixée au lait de coco.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Banane, lait, miel, glaçons" },
  { id: "44", category_id: "smoothies", name: "Smoothie Blue Berry", description: "Mûres et myrtilles sauvages mixées.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Myrtilles, yaourt, lait, glaçons" },
  { id: "45", category_id: "smoothies", name: "Smoothie Banana Colada", description: "Cocktail gourmand banane, ananas et coco.", price: 650, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Banane, jus d'ananas, coco, glaçons" },
  { id: "46", category_id: "smoothies", name: "Smoothie Miami Beach Mango", description: "Mangue tropicale mixée ultra-fraîche.", price: 650, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Mangue mûre, jus d'orange, glaçons" },

  // ==================== MILKSHAKES (Milkshakes) ====================
  { id: "47", category_id: "milkshakes", name: "Milkshake Classic", description: "Milkshake crémeux classique à la vanille.", price: 550, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Glace vanille, lait, crème fouettée" },
  { id: "48", category_id: "milkshakes", name: "Milkshake Banana", description: "Glace vanille et banane fraîche mixées.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Banane, lait, crème" },
  { id: "49", category_id: "milkshakes", name: "Milkshake Chocolate", description: "Milkshake riche au cacao et chocolat.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Chocolat fondu, crème, lait" },
  { id: "50", category_id: "milkshakes", name: "Milkshake Oreo", description: "Le célèbre biscuit Oreo mixé avec de la glace.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Biscuits Oreo, glace vanille, lait" },
  { id: "51", category_id: "milkshakes", name: "Milkshake Biscuit Caramel", description: "Gourmandise au spéculoos et filet de caramel.", price: 650, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Biscuit spéculoos, caramel, glace vanille" },
  { id: "52", category_id: "milkshakes", name: "Milkshake Overdose", description: "Une explosion de douceurs sucrées superposées.", price: 650, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Chocolat, caramel, biscuits, topping géant" },
  { id: "53", category_id: "milkshakes", name: "Milkshake Pistachio", description: "Pistache d'Italie crémeuse et éclats de pistaches.", price: 700, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: true, featured: true, promotion: false, ingredients: "Pistache, lait, glace premium, toppings" },

  // ==================== GATEAUX (Viennoiserie) (desserts) ====================
  { id: "54", category_id: "desserts", name: "Croissant Beurre", description: "Croissant au beurre français, croustillant et chaud.", price: 120, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Pâte feuilletée, beurre" },
  { id: "55", category_id: "desserts", name: "Pain au Chocolat", description: "Feuilletage doré fourré de deux barres de chocolat.", price: 120, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Pâte feuilletée, barres de chocolat" },
  { id: "56", category_id: "desserts", name: "Cookie Pistachio", description: "Cookie moelleux aux éclats de pistache verte.", price: 300, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Pâte à cookie, pistaches concassées" },
  { id: "57", category_id: "desserts", name: "Cookie Chocolat", description: "Cookie traditionnel aux pépites de chocolat noir.", price: 300, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Cookie, pépites de chocolat" },
  { id: "58", category_id: "desserts", name: "Cookie Chocolat Pistache", description: "Le duo parfait : chocolat fondant et pistaches croquantes.", price: 300, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Cookie, chocolat noir, éclats de pistaches" },
  { id: "59", category_id: "desserts", name: "Cookie Lotus", description: "Cookie gourmand fourré au spéculoos Lotus.", price: 300, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Cookie, crème de spéculoos Lotus" },
  { id: "60", category_id: "desserts", name: "Honey Cake", description: "Gâteau au miel russe traditionnel à couches superposées.", price: 300, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Miel d'abeille, crème fraîche, biscuit" },
  { id: "61", category_id: "desserts", name: "Marble Cake", description: "Cake marbré vanille et chocolat à l'ancienne.", price: 300, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Cake marbré vanille-cacao" },
  { id: "62", category_id: "desserts", name: "Gourmand Cake", description: "Part de cake extra-moelleux garnie de topping.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Cake gourmand maison" },
  { id: "63", category_id: "desserts", name: "Brownie Chocolat", description: "Brownie chocolat noir et noix de pécan.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Chocolat noir, noix de pécan, beurre" },
  { id: "64", category_id: "desserts", name: "Brownie Lotus", description: "Brownie moelleux garni de brisures de Lotus.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Brownie chocolat, spéculoos Lotus" },
  { id: "65", category_id: "desserts", name: "Matilda Cake", description: "Le fameux gâteau géant au chocolat ultra-coulant.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: true, featured: true, promotion: false, ingredients: "Gâteau géant au chocolat, ganache fondante" },
  { id: "66", category_id: "desserts", name: "San Sebastian Cheesecake", description: "Cheesecake basque brûlé servi avec chocolat chaud fondu.", price: 600, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: true, featured: true, promotion: false, ingredients: "Fromage à la crème, coulis de chocolat au choix" },
  { id: "67", category_id: "desserts", name: "Tarte Chocolat Caramel", description: "Pâte sablée croquante, caramel au beurre salé et ganache chocolat.", price: 400, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Sablé, caramel salé, ganache" },
  { id: "68", category_id: "desserts", name: "Tarte à la Pêche", description: "Tartelette fruitée garnie de pêches caravélisées.", price: 400, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Pâte sablée, crème d'amande, pêches" },
  { id: "69", category_id: "desserts", name: "Tarte Banane + Glace", description: "Tarte gourmande à la banane cuite servie avec sa boule de glace.", price: 450, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: true, promotion: false, ingredients: "Banane, pâte sablée, glace vanille" },
  { id: "70", category_id: "desserts", name: "Cheesecake Chocolat", description: "Cheesecake crémeux marbré au chocolat noir.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Fromage, biscuit, ganache chocolat" },
  { id: "71", category_id: "desserts", name: "Cheesecake Fraise", description: "Cheesecake classique surmonté d'un coulis de fraises fraîches.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Coulis de fraises fraîches, fromage de spécialité" },
  { id: "72", category_id: "desserts", name: "Cheesecake Citron", description: "Fraîcheur acidulée du citron vert.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Crémeux citron, base biscuitée croustillante" },
  { id: "73", category_id: "desserts", name: "Cheesecake Pistache", description: "Le croquant de la pistache concassée sur lit crémeux.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Crème de pistache d'Italie, éclats" },
  { id: "74", category_id: "desserts", name: "Cheesecake Lotus", description: "Gourmandise ultime fourrée et glacée au spéculoos Lotus.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Biscuit spéculoos Lotus, fromage onctueux" },
  { id: "75", category_id: "desserts", name: "Trompe-l'oeil Mangue", description: "Dessert en forme de vraie mangue renfermant une mousse onctueuse.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Mousse mangue-passion, coque en chocolat coloré" },
  { id: "76", category_id: "desserts", name: "Trompe-l'oeil Café", description: "Dessert en trompe-l'œil en forme de grain de café géant.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Mousse café intense Arabica, ganache" },

  // ==================== SALES (snacks-sales) ====================
  { id: "77", category_id: "snacks-sales", name: "Batbout", description: "Pain batbout farci de viande marinée et crudités.", price: 150, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Pain marocain farci, poulet mariné, salade" },
  { id: "78", category_id: "snacks-sales", name: "Mini Pizza", description: "Mini pizza garnie de sauce tomate, fromage et olive.", price: 150, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Tomate, mozzarella, olives" },
  { id: "79", category_id: "snacks-sales", name: "Pizza Carrée", description: "Pizza carrée traditionnelle garnie.", price: 150, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Pâte à pizza, sauce tomate maison, fromage" },
  { id: "80", category_id: "snacks-sales", name: "Taco", description: "Taco croustillant garni de poulet et de sauces.", price: 150, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Tortilla de blé, viande, frites, sauce fromage" },
  { id: "81", category_id: "snacks-sales", name: "Mini Burger", description: "Bouchée gourmande au bœuf et cheddar fondu.", price: 200, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Mini pain burger, steak, cheddar" },
  { id: "82", category_id: "snacks-sales", name: "Quiche", description: "Quiche salée traditionnelle croustillante.", price: 200, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Crème, œufs, fromage râpé, pâte brisée" },
  { id: "83", category_id: "snacks-sales", name: "Sandwich Poulet", description: "Pain ciabatta garni de poulet grillé et de sauces.", price: 350, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Pain spécial, escalope de poulet, sauces au choix" },
  { id: "84", category_id: "snacks-sales", name: "Croissant Turkey", description: "Croissant chaud garni d'omelette et tranches de dinde fumée.", price: 400, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Croissant, dinde fumée, omelette, fromage" },
  { id: "85", category_id: "snacks-sales", name: "Omelette Classique", description: "Omelette traditionnelle baveuse cuite à la poêle.", price: 500, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Oeufs frais, sel, poivre" },
  { id: "86", category_id: "snacks-sales", name: "Omelette 3 Fromages", description: "Omelette ultra-fondante aux trois fromages sélectionnés.", price: 700, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Oeufs, emmental, cheddar, mozzarella" },
  { id: "87", category_id: "snacks-sales", name: "Omelette Avocat", description: "Omelette fraîche servie avec tranches d'avocat crémeux.", price: 1200, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Oeufs, tranches d'avocat frais, fines herbes" },
  { id: "88", category_id: "snacks-sales", name: "Petit Déjeuner du Jour", description: "La surprise du chef pour démarrer la journée du bon pied.", price: 800, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Formule changeante selon l'humeur du chef" },
  { id: "89", category_id: "snacks-sales", name: "Petit Déjeuner Classique", description: "Formule complète avec boissons et viennoiserie.", price: 1200, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Viennoiserie, café au choix, jus d'orange pressé, toasts" },
  { id: "90", category_id: "snacks-sales", name: "Petit Déjeuner Avocat", description: "Formule saine et gourmande à base d'avocat.", price: 1800, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Toast avocat, œuf poché, jus d'orange pressé, thé/café" },
  { id: "91", category_id: "snacks-sales", name: "Brunch Français", description: "Brunch traditionnel au parfum parisien.", price: 900, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Baguette fraîche, confiture, beurre, croissant, boisson chaude" },
  { id: "92", category_id: "snacks-sales", name: "Brunch Avocat", description: "Brunch frais et nourrissant.", price: 1200, media_type: "image", media_url: "/logo.jpg", available: true, best_seller: false, featured: false, promotion: false, ingredients: "Grand pain de campagne grillé, purée d'avocat, saumon/dinde" },
];

const NEW_CATEGORIES = [
  { id: "coffee", name: { fr: "Boissons chaudes", en: "Hot Drinks", ar: "مشروبات ساخنة" }, icon: "☕", sort_order: 1 },
  { id: "cold-drinks", name: { fr: "Boissons fresh", en: "Fresh Drinks", ar: "مشروبات منعشة" }, icon: "🧊", sort_order: 2 },
  { id: "mocktails", name: { fr: "Mocktail", en: "Mocktail", ar: "موكتيل" }, icon: "🍹", sort_order: 3 },
  { id: "smoothies", name: { fr: "Smoothies", en: "Smoothies", ar: "سموذي" }, icon: "🥑", sort_order: 4 },
  { id: "milkshakes", name: { fr: "Milkshakes", en: "Milkshakes", ar: "ميلك شيك" }, icon: "🥤", sort_order: 5 },
  { id: "desserts", name: { fr: "Gâteaux (viennoiserie)", en: "Pastries & Desserts", ar: "حلويات ومخبوزات" }, icon: "🍰", sort_order: 6 },
  { id: "snacks-sales", name: { fr: "Salés", en: "Salty Snacks", ar: "مملحات" }, icon: "🍕", sort_order: 7 },
];

// Let's modify useProductStore.ts
const useProductStorePath = path.join(__dirname, '../src/store/useProductStore.ts');
let content = fs.readFileSync(useProductStorePath, 'utf8');

// 1. Replace INITIAL_PRODUCTS block
const startIdx = content.indexOf('const INITIAL_PRODUCTS');
const endIdx = content.indexOf('interface ProductState');
if (startIdx !== -1 && endIdx !== -1) {
  const newProductsStr = 'const INITIAL_PRODUCTS: StoreProduct[] = ' + JSON.stringify(NEW_PRODUCTS_JSON, null, 2) + ';\n\n';
  content = content.substring(0, startIdx) + newProductsStr + content.substring(endIdx);
}

// 2. Replace defaultCategories inside resetToDefaultMenu
const categoriesStart = content.indexOf('const defaultCategories = [');
const categoriesEnd = content.indexOf('];', categoriesStart);
if (categoriesStart !== -1 && categoriesEnd !== -1) {
  const newCategoriesStr = 'const defaultCategories = ' + JSON.stringify(NEW_CATEGORIES, null, 2);
  content = content.substring(0, categoriesStart) + newCategoriesStr + content.substring(categoriesEnd + 2);
}

fs.writeFileSync(useProductStorePath, content, 'utf8');
console.log("Successfully reclassified useProductStore.ts!");
